 $bodyContent:{
 $it.rows:{
   <Row>
    <Cell><Data ss:Type="String">$it.name1$</Data></Cell>
    <Cell><Data ss:Type="String">$it.name2$</Data></Cell>
    <Cell><Data ss:Type="String">$it.name3$</Data></Cell>
    <Cell><Data ss:Type="String">$it.name4$</Data></Cell>
    <Cell><Data ss:Type="String">$it.name5$</Data></Cell>
    <Cell><Data ss:Type="String">$it.name6$</Data></Cell>
   </Row>
 }$
}$

